name: Build for Desktop

on:
  push:
  release:
    types: [prereleased]

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    name: '${{ matrix.config.name }} (No RouteEditor: ${{ matrix.no_route_editor }})'
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        no_route_editor: [ON, OFF]
        config:
        - {
            name: "Windows MSVC", artifact: "Windows",
            os: windows-latest,
            cc: "cl.exe", cxx: "cl.exe",
            arch: "win64_msvc2019_64",
            has_msvc: true,
            has_release: true,
            vcpkgTriplet: x64-windows
          }
        - {
            name: "Ubuntu", artifact: "Linux",
            os: ubuntu-latest,
            has_release: false,
            vcpkgTriplet: x64-linux
          }
        - {
            name: "macOS", artifact: "macOS",
            os: macos-latest,
            has_release: true,
            vcpkgTriplet: x64-osx
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install MSVC compiler
      if: matrix.config.has_msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 6.2.0
        arch: ${{ matrix.config.arch }}
        aqtversion: ==1.2.2

    - name: Install Vulkan SDK
      if: matrix.config.os != 'macos-latest'
      uses: humbletim/setup-vulkan-sdk@v1.0.2

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v7.3
      with:
        vcpkgArguments: protobuf openssl grpc libuv uvw
        vcpkgGitCommitId: c69096659f49e2b1aca532ea5c2f8c135182519b
        vcpkgTriplet: ${{ matrix.config.vcpkgTriplet }}
  
    - name: Build
      run: |
        mkdir build; cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=installed \
          -DBUILD_TESTING=OFF \
          -DUSE_SYSTEM_LIBUV=OFF \
          -DUSE_SYSTEM_UVW=OFF \
          -DQV2RAY_NO_NODEEDITOR=${{ matrix.no_route_editor }} \
          -GNinja
        cmake --build . --parallel

    - name: Install
      run: |
        cd build
        cmake --install .

    - name: Generate 7zip
      run: 7z a QvPersonal.7z -- build/installed

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: QvPersonal-${{ github.sha }}-${{ matrix.config.artifact }}.7z
        path: QvPersonal.7z

    - name: Get the version
      if: github.event_name == 'release' && matrix.config.has_release && matrix.no_route_editor == 'OFF'
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Upload to GitHub Release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release' && matrix.config.has_release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: QvPersonal.7z
        asset_name: QvPersonal-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.artifact }}.7z
        tag: ${{ github.ref }}
        overwrite: true
